### ISSUE TITLE
Reorganize hardware_platforms

### ISSUE THREAD

**Issue by stephenhensley** [electro-smith/DaisyExamples#1]
Right now there are several examples that aren't for the hardware specified by the location or name of the project..

Namely, seed/examples/WavPlayer, and pod/examples/PodVs are incorrect. WavPlayer uses the DaisyPod, and PodVs uses the Patch.

On top of that I think having the extra level of folders is unnecessary.

There could just be project folders in each hardware device. so hardware_platforms/pod/Musicbox, etc. 

won't be hard to move them (makefiles will need to be edited). But all of these will likely need a significant touch up shortly anyway.

We're currently ironing out the daisy_* files in libdaisy to provide a clean interface for users.

**Comment by erwincoumans** [comment]
Would the WavPlayer work for patch as well?
