### ISSUE TITLE
DaisyExamples/field/Midi/resources: Files are for Daisy Patch

### ISSUE THREAD

**Issue by anthroid** [electro-smith/DaisyExamples#100]
DaisyExamples/field/Midi/resources/Midi.png,Midi.ai are for the Daisy Patch. Missing these documents for the Field.

**Comment by stephenhensley** [comment]
Just fixed this!

**Comment by stephenhensley** [comment]
We don't have a new product photo so I have updated README, etc for the current example and hardware, but we do not have a diagram for the Field yet.
