### ISSUE TITLE
DaisyExamples/resources: Template files are for pre-production version of the Field (no OLED, no 8x2 grid)

### ISSUE THREAD

**Issue by anthroid** [electro-smith/DaisyExamples#101]
DaisyExamples/resources:
- fieldExampleTemplate.ai: Document shows an old/outdated version of the Field (no OLED, 13 buttons).
- png/fieldExampleTemplate.png: Same as .ai version.

**Comment by andrewikenberry** [comment]
up to date files are in repo now
