### ISSUE TITLE
Hardware/resources/fieldPinout.ai: Documents are for pre-release Daisy Field

### ISSUE THREAD

**Issue by anthroid** [electro-smith/DaisyExamples#104]
Hardware/resources/fieldPinout.ai: Documents are for pre-release Daisy Field without the OLED/new switch layout.

**Comment by anthroid** [comment]
Also derived files 300ppi/fieldPinout.png, 4x/fieldPinout.png.

**Comment by andrewikenberry** [comment]
files are now up to date
