### ISSUE TITLE
DaisyExamples/petal/MultiEffect: Firmware update suggestions/ bug fixes

### ISSUE THREAD

**Issue by corellmichael** [electro-smith/DaisyExamples#112]
Per @manysounds on the Forum:

- Swap Switch 1/LED1 with Switch 2/LED2

- Default mix for all effects/master should be set to 50% instead of 0%

- if possible, add persistent memory for mix amounts between power cycles

- Bug: Bitcrush occasionally gets stuck on (I am unable to recreate this)

- Bug: Reverb buffer glitches out (also have yet to recreate).

  - claims Daisy seed RESET resolves bugs above

**Comment by beserge** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Multieffect Petal Example](https://trello.com/c/EcZO2Ky0/55-multieffect-petal-example)
