### ISSUE TITLE
Make Create New Project Python Script

### ISSUE THREAD

**Issue by andrewikenberry** [electro-smith/DaisyExamples#126]

**Comment by andrewikenberry** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create New Project Python Script](https://trello.com/c/PvKL9Zif/64-create-new-project-python-script)

**Comment by stephenhensley** [comment]
Just weighing in before the PR shows up, but this is much needed especially as Debug support gets added to all the examples.

After doing a very brief amount of playing around with VCV rack a week or so ago, it was cool to see their python helper script, `helper.py`, be a singular script to assist with most utility actions. Might be worth doing something similar here to limit the number of scripts needed.

could be like:

```
#  Create MyNewProject for DaisyPatch
python helper.py create --board patch MyNewProject

# Duplicate MyOldProject and and rename everything to MyNewProject
python helper.py duplicate MyOldProject MyNewProject
```

the long-form  `--board` could be `-b` or just a second positional argument.

**Comment by stephenhensley** [comment]
works as part of helper.py
