### ISSUE TITLE
Small error in Seed > Drum.cpp when mixing the two sounds

### ISSUE THREAD

**Issue by StaffanMelin** [electro-smith/DaisyExamples#135]
Hi,

DaisyExamples/seed/Drum/Drum.cpp:

Line 60:
`sig = .5 * noise_out + .5 + osc_out;`
should be:
`sig = .5 * noise_out + .5 * osc_out;`

The same error appears in EuclidianDrums.cpp, too, on line 48.

**Comment by beserge** [comment]
Good catch! #136 fixes this.

**Comment by StaffanMelin** [comment]
Great!

I just started with Daisy yesterday so I am happy that I can help already! :)
