### ISSUE TITLE
vscode tasks.json build_daisysp case sensitive

### ISSUE THREAD

**Issue by ifranco** [electro-smith/DaisyExamples#162]
In line 47 of the vscode tasks.json file, "daisysp" should be changed to "DaisySP", since it's case sensitive.

**Comment by stephenhensley** [comment]
Oh, good catch. I've been working on Windows and I did not catch this! I'll get it fixed ASAP!

**Comment by stephenhensley** [comment]
oh actually it looks like @nvmker patched this up in his improvements a few weeks ago 

😄
