### ISSUE TITLE
Directories not escaped in ci/build_libs.sh results in failure when path contains spaces

### ISSUE THREAD

**Issue by johnnyhoffman** [electro-smith/DaisyExamples#165]
The LIBDAISY_DIR and DAISYSP_DIR usages in cd trigger error "cd: too many arguments" when the values contain spaces (e.g. I have the files under a lop level "Google Drive" fold that is everything I have cloud sync set up for). Putting quotes around the usages seems to do the trick,

**Comment by stephenhensley** [comment]
Good to know! We'll look into fixing this!
