### ISSUE TITLE
libdaisy submodule 404 error

### ISSUE THREAD

**Issue by ggsubs** [electro-smith/DaisyExamples#20]
The libdaisy submodule points to a non-accessible Github URL: https://github.com/andrewikenberry/ES_libdaisy/ - thus the builds are failing.

**Comment by stephenhensley** [comment]
@ggsubs the libdaisy repo is going to be going live very shortly. 

I'll comment again when its live!

**Comment by stephenhensley** [comment]
Alright! @ggsubs 

the link to libdaisy has been fixed, and the repo is live!

Should be good to go! (The blink example mentioned in the Wiki's Getting Started section is also now in this repo in case you were following along with that guide).
