### ISSUE TITLE
seed/faustnoise - no longer compiles due to ambiguous UI class

### ISSUE THREAD

**Issue by stephenhensley** [electro-smith/DaisyExamples#206]
This is due to the addition of daisy::UI while there is a `UI` class in the faust/gui folder.

Should be resolvable by using explicity `daisy::` namespacing and removing `using namespace daisy;`

**Comment by sletz** [comment]
I've (blindly...) fixed the faust2daisy template file here, https://github.com/grame-cncm/faust/commit/e55632ccef4318df82b165e12eba41fb0c93cb91, following your fix.

**Comment by stephenhensley** [comment]
@sletz awesome, thanks! I was just about to reach out to let you know. Hope you've been well!
