### ISSUE TITLE
SDMMC example needs configure call

### ISSUE THREAD

**Issue by CorvusPrudens** [electro-smith/DaisyExamples#221]
The SDMMC example in seed just needs the `Configure` method called before init. Really simple, just thought I'd put this here so I don't forget to update that. If you run into issues with the QSPI init that seem totally random, double check that your project is _definitely_ configured before initialization.

**Comment by stephenhensley** [comment]
woah, good catch. I'm guessing this was originally for the Pod or something.

@CorvusPrudens I can merge the fix if you want to open a PR (even though we'll be removing the Configure step in one of the upcoming libDaisy updates).

**Comment by stephenhensley** [comment]
not anymore!

we can actually remove the configure call from _all_ examples. It is now a deprecated function.
