### ISSUE TITLE
some references in patch_sm READMEs to restricted repo DaisyPatchSM

### ISSUE THREAD

**Issue by matpalm** [electro-smith/DaisyExamples#234]
small fyi that there's a number of references in READMEs to https://github.com/electro-smith/DaisyPatchSM which appears to not be public (yet?)

**Comment by stephenhensley** [comment]
That's correct. 

The DaisyPatchSM repo is currently private. We will be making it public when the device is officially released.

**Comment by matpalm** [comment]
ahha. no problem, look forward to reading about it
