### ISSUE TITLE
"PNG" diagrams are missing

### ISSUE THREAD

**Issue by znmeb** [electro-smith/DaisyExamples#255]
So far, almost every diagram I've tried to open is getting a 404 not found`. I'm guessing they were here once upon a time though, and it's just the links in the `README.md` files that are broken.

**Comment by stephenhensley** [comment]
Hi @znmeb 

We did have diagrams for each example. These have been stripped out (the tables in the markdown provide the same detail), but don't take up a ton of space in the already very large repository.

We do plan on adding visual diagrams for many examples (especially seed examples that require making hardware connections), and hosting them outside of github.

We'll leave this open until we go through and strip out all of the broken links.
