### ISSUE TITLE
empty file at /seed/Knob/resources/Knob.fzz

### ISSUE THREAD

**Issue by jordanmichaelfrancis** [electro-smith/DaisyExamples#260]
The Fritzing file for the seed's knob example is empty:

<img width="930" alt="Screen Shot 2022-01-26 at 12 21 12 PM" src="https://user-images.githubusercontent.com/7292199/151240803-b3ffd07b-1218-4f45-a202-89eaa2079895.png">

When opened in Fritzing, the file produces the following error message:

> Unable to open '/Users/jordanfrancis/code/repos/DaisyExamples/seed/Knob/resources/Knob.fzz': zip.open(): %d 

<img width="1131" alt="Screen Shot 2022-01-26 at 12 19 59 PM" src="https://user-images.githubusercontent.com/7292199/151240815-8c795521-7655-4227-9620-24df9c7bff27.png">

**Comment by stephenhensley** [comment]
Oh no! 

Thanks for letting us know, we'll look into this. And try to get it fixed ASAP.

**Comment by stephenhensley** [comment]
@jordanmichaelfrancis thanks again for pointing this out. Should be resolved!
