### ISSUE TITLE
seed/WavPlayer.cpp stopped working with FatFSInterface

### ISSUE THREAD

**Issue by MarianoDesivo** [electro-smith/DaisyExamples#261]
On previous versions I used to have no Fat FS Interface, and my daisy seed can run this example at STANDARD speed - 1 bit width

But now I can't use it, it seems the Daisy can not read the SD card

I have connected the SD card d0 bit and CMD with 47k pull up resistors, and to the Daisy sd pins (also connected clk, 3v3, and gnd)

![image](https://user-images.githubusercontent.com/79780807/151484455-d9b60333-7b3c-4ab6-a86a-e8594510b304.png)
This is my circuit, same as daisyPod circuit but with only 1 bit (d0). DGND is connected to AGND

**Comment by stephenhensley** [comment]
@MarianoDesivo Is it possible that you had a modified version of the file before updating?

The default for the SDMMC handler is 4-bit I/O. 

If you add the following line after `sd_cfg.Defaults();` it should work for you again:

```cpp
sd_cfg.width = SdmmcHandler::BusWidth::BITS_1;
```
