### ISSUE TITLE
DaisyDuino Update

### ISSUE THREAD

**Issue by Pachicito** [electro-smith/DaisyExamples#280]
My Thanksgiving wishlist. :) 
- Make DaisyDuino 1.6.1 available from the Arduino library manager.
- Update examples including examples for Versio and Legio from Noise Engineering

**Comment by stephenhensley** [comment]
@Pachicito 

wow, none of us realized the v1.6.1 didn't end up in the Arduino library manager! Thanks for pointing this out.

I just moved your issues over to the DaisyDuino repo. Thanks for the requests! :)
