### ISSUE TITLE
Osc code vs schematics

### ISSUE THREAD

**Issue by Iliceth** [electro-smith/DaisyExamples#71]
Hi

The code addresses pins 21 (knob) and 28 (button), while the schematic has 28 and 35 respectively, so I assume an error? 

Kind regards

**Comment by stephenhensley** [comment]
Hi, the code uses a pin numbering system that doesn't include supply pins or the audio pins. If you look at the schematic symbol these are the GPIO numbers indicated there.

**Comment by Iliceth** [comment]
Thanks for the clarification. I'm used to refering to physical pins in schematics, therefor the mistake on my end.
