### ISSUE TITLE
Field example KeyboardTest to building.

### ISSUE THREAD

**Issue by h-iggs** [electro-smith/DaisyExamples#97]
When I use the web dfu programmer to upload the keyboard test demo already built by you guys it works fine. But the one in the repo doesn't build due to "DaisyField" not existing. Someone forgot to push changes to github? DaisyField does exist in libDaisy/daisy_field.cpp but it has no knob or other consts in it. 

Thanks

KeyboardTest.cpp:8:1: error: 'DaisyField' does not name a type
    8 | DaisyField hw;
      | ^~~~~~~~~~

**Comment by stephenhensley** [comment]
There's a chance that your libdaisy submodule is out of date. Updating repositories with submodules is a bit of a pain sometimes, but you can try:
`git pull --recurse-submodules`, `git submodule update`, or you can navigate into the the libdaisy directory, and do `git checkout master; git pull;` there. 

At times the submodule does end up lagging a few days behind the master branch as they are separate projects, but we do try our best to make sure all of the examples keep building as anything in the libraries change.

The earlier version of the daisy field was a C struct named `daisy_field` which may be why you're seeing the error.

**Comment by h-iggs** [comment]
Yeah that was it :)
Thank you Stephen. I just re-cloned the whole repo and built and flashed the keyboard demo and it works fine.

Thanks :)
